# wrangler.toml
name = "cloudflare-serverless-todo" # Ganti dengan nama unik untuk proyek Worker Anda
main = "worker-backend/src/index.js" # Pastikan ini mengarah ke file utama kode Worker Anda (misalnya: src/index.js)
compatibility_date = "2025-06-14" # Selalu gunakan tanggal kompatibilitas terbaru (sesuai hari ini)

[observability.logs]
enabled = true

[[kv_namespaces]]
binding = "TODO_LIST_DATA"
id = "3c69acf722ba4949a79c01f436441e14"
preview_id = "3c69acf722ba4949a79c01f436441e14"
